version: '3.7'

services:
    backend:
        build: ./backend
        image: rnskv/inferno_backend
        ports:
            - '6001:6001'
        depends_on:
            - db
            - redis
        container_name: inferno_backend
    realtime:
        build: ./realtime
        image: rnskv/inferno_realtime
        ports:
            - '6002:6002'
        depends_on:
            - backend
        container_name: inferno_realtime
    client:
        build: ./client
        image: rnskv/inferno_client
        ports:
            - '6003:6003'
        depends_on:
            - realtime
        container_name: inferno_client
    deamons:
        build: ./deamons
        image: rnskv/inferno_deamons
        depends_on:
            - realtime
        container_name: inferno_deamons
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: inferno_db
    redis:
        image: redis
        sysctls:
            net.core.somaxconn: 1024
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --requirepass kjashdhqe!i321lDdasd
        container_name: inferno_redis
    nginx:
        restart: always
        build: ./nginx/
        image: rnskv/inferno_nginx
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:6004:6004"
            - "0.0.0.0:6005:6005"
        links:
            - client:client