version: '3.7'

services:
    backend:
        build: ./backend
        image: rnskv/inferno_backend
        ports:
            - '6001:6001'
        depends_on:
            - db
            - redis
        container_name: inferno_backend
        networks:
            - app-network
    realtime:
        build: ./realtime
        image: rnskv/inferno_realtime
        ports:
            - '6002:6002'
        depends_on:
            - backend
        container_name: inferno_realtime
        networks:
            - app-network
    client:
        build: ./client
        image: rnskv/inferno_client
        ports:
            - '6003:6003'
        depends_on:
            - realtime
        container_name: inferno_client
        networks:
            - app-network
    deamons:
        build: ./deamons
        image: rnskv/inferno_deamons
        depends_on:
            - realtime
        container_name: inferno_deamons
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: inferno_db
    redis:
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --requirepass kjashdhqe!i321lDdasd
        container_name: inferno_redis
    nginx:
        restart: always
        build: ./nginx/
        image: rnskv/inferno_nginx
        ports:
            - "80:80"
        volumes_from:
            - web
        links:
            - client:client