export const CASHIER_CHANGE_DEPOSIT_TAB = 'CASHIER_CHANGE_DEPOSIT_TAB';
export const CASHIER_CHANGE_WITHDRAW_TAB = 'CASHIER_CHANGE_WITHDRAW_TAB';
export const CASHIER_CHANGE_VALUE = 'CASHIER_CHANGE_VALUE';

export const CASHIER_LOADING_START = 'CASHIER_LOADING_START';
export const CASHIER_LOADING_STOP = 'CASHIER_LOADING_STOP';
