export const SERVER_ERROR = 'SERVER_ERROR';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const REDIRECT_MESSAGE = 'REDIRECT_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const INFORMATION_MESSAGE = 'INFORMATION_MESSAGE';
