export const SET_REFERRALS_STATISTIC = 'SET_REFERRALS_STATISTIC';

export const SET_STATISTICS_IS_LOADING = 'SET_STATISTICS_IS_LOADING';
export const SET_CASH_OUT_IS_LOADING = 'SET_CASH_OUT_IS_LOADING';
