export const OPEN_BET_MAKER = 'OPEN_BET_MAKER';
export const CLOSE_BET_MAKER = 'CLOSE_BET_MAKER';
export const ADD_ITEM_IN_BET_MAKER = 'ADD_ITEM_IN_BET_MAKER';
export const REMOVE_ITEM_FROM_BET_MAKER = 'REMOVE_ITEM_FROM_BET_MAKER';
export const BET_MAKER_ADD_ITEMS = 'BET_MAKER_ADD_ITEMS';
