export const OPEN_BET_MAKER = 'OPEN_BET_MAKER';
export const CLOSE_BET_MAKER = 'CLOSE_BET_MAKER';
export const ADD_BET_IN_BET_MAKER = 'ADD_BET_IN_BET_MAKER';
export const REMOVE_BET_FROM_BET_MAKER = 'REMOVE_BET_FROM_BET_MAKER';
