export const USER_ALREADY_EXIST = 'USER_ALREADY_EXIST';
export const USER_WRONG_PASSWORD = 'USER_WRONG_PASSWORD';
export const USER_WRONG_REGISTER_DATA = 'USER_WRONG_REGISTER_DATA';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_NOT_AUTH = 'USER_NOT_AUTH';
export const USER_NOT_ENOUGH_MONEY = 'USER_NOT_ENOUGH_MONEY';
export const USER_WIN = 'USER_WIN';
export const USER_SUCCESS_REGISTER = 'USER_SUCCESS_REGISTER';
export const USER_NOT_SELECT_ITEMS = 'USER_NOT_SELECT_ITEMS';
export const USER_NOT_ENOUGHT_ACCESS_RIGHT = 'USER_NOT_ENOUGHT_ACCESS_RIGHT';
export const USER_HAS_NOT_ITEMS = 'USER_HAS_NOT_ITEMS';
export const USER_CREATE_STEAM_ITEMS_WITHDRAW = 'USER_CREATE_STEAM_ITEMS_WITHDRAW';

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const BET_SENDING = 'BET_SENDING';
export const BET_ACCEPTED = 'BET_ACCEPTED';

export const GAME_CLOSED_FOR_BETS = 'GAME_CLOSED_FOR_BETS';

export const REALTIME_DISCONNECTED = 'REALTIME_DISCONNECTED';

export const WAITING_LAST_BETS = 'WAITING_LAST_BETS';
export const SO_MANY_ITEMS = 'SO_MANY_ITEMS';

export const WITHDRAW_CREATED_QIWI = 'WITHDRAW_CREATED_QIWI';
export const WITHDRAW_ERROR_DATA_QIWI = 'WITHDRAW_ERROR_DATA_QIWI';
export const WITHDRAW_ERROR_MIN_AMOUNT = 'WITHDRAW_ERROR_MIN_AMOUNT';

export const TRADEOFFER_ACCEPTED = 'TRADEOFFER_ACCEPTED';
export const TRADEOFFER_VERIFY_CODE = 'TRADEOFFER_VERIFY_CODE';
export const TRADEOFFER_SENT_ERROR = 'TRADEOFFER_SENT_ERROR';

export const INVENTORY_ITEMS_ADDED = 'INVENTORY_ITEMS_ADDED';

export const STEAM_TRADE_URL_ALREADY_TAKEN = 'STEAM_TRADE_URL_ALREADY_TAKEN';
export const STEAM_TRADE_URL_MIN_LENGTH = 'STEAM_TRADE_URL_MIN_LENGTH';
export const STEAM_TRADE_URL_CHANGED = 'STEAM_TRADE_URL_CHANGED';

export const EMPTY_ITEM_COST = 'EMPTY_ITEM_COST';
export const FORBIDDEN_TAKE_ITEMS = 'FORBIDDEN_TAKE_ITEMS';
export const USER_NOT_REGISTER = 'USER_NOT_REGISTER';
