export const USER_ALREAY_EXIST = 'USER_ALREAY_EXIST';
export const USER_WRONG_PASSWORD = 'USER_WRONG_PASSWORD';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_NOT_AUTH = 'USER_NOT_AUTH';
export const USER_NOT_ENOUGH_MONEY = 'USER_NOT_ENOUGH_MONEY';
export const USER_WIN = 'USER_WIN';

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const TRANSACTION_SENDING = 'TRANSACTION_SENDING';
export const TRANSACTION_ACCEPTED = 'TRANSACTION_ACCEPTED';

export const GAME_CLOSED_FOR_TRANSACTIONS = 'GAME_CLOSED_FOR_TRANSACTIONS';

export const REALTIME_DISCONNECTED = 'REALTIME_DISCONNECTED';