export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOADING_USER = 'LOADING_USER';
export const ERROR_USER = 'ERROR_USER';
export const RESET_USER = 'RESET_USER';
export const ADD_NOTIFICATION = 'GET_NOTIFICATION';

export const SET_PROFILE = 'SET_PROFILE';
export const CHANGE_BALANCE_USER = 'CHANGE_BALANCE_USER';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
